name: "test action"

on:
  workflow_dispatch:

permissions:
  contents: "read"

defaults:
  run:
    shell: "bash"
    working-directory: "."

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "test"
        run: |
          file=$(mktemp)
          echo 'hello' >> "$file"
          echo "$(cksum -a sha256 --untagged "$@" ${file})"
          echo "$(cksum -a sha256 --untagged ${file})"
          version=$(jq -rn '""')
          if [[ -z "$version" ]]; then
            echo '::error::invalid "packageManager" in package.json\naaaa'
            echo 'bbbbbbbb'
            exit;
          fi
